#!/bin/bash

. "$EUPS_DIR/lib/eupspkg.sh"

# Breaks on Darwin w/o this
export LANG=C

config()
{
	echo "STARTING XROOTD BUILD IN $PWD"
	cd ..
	echo "CONFIGURING XROOTD IN $PWD"
	cmake ${PKGDIR} -DCMAKE_INSTALL_PREFIX=${PREFIX} -DENABLE_PERL=FALSE
}

"$@"
